function [Hd,N] = butterworthfilter
%BUTTERWORTHFILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.6 and the DSP System Toolbox 9.1.
% Generated on: 01-Nov-2018 21:56:52

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in kHz.
Fs = 200;  % Sampling Frequency

Fstop1 = 5;           % First Stopband Frequency
Fpass1 = 6;           % First Passband Frequency
Fpass2 = 14;          % Second Passband Frequency
Fstop2 = 15;          % Second Stopband Frequency
Astop1 = 48;          % First Stopband Attenuation (dB)
Apass  = 1;           % Passband Ripple (dB)
Astop2 = 48;          % Second Stopband Attenuation (dB)
match  = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass(Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, ...
                      Astop2, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);
N=76;%½×Êý

% [EOF]
